version: '3.8'

services:
  # Servidor WebSocket (Python)
  websoker:
    build:
      context: ./websoker
      dockerfile: Dockerfile
    container_name: proyecto-autonomo-websoker
    ports:
      - "8000:8000"
    environment:
      WEBSOCKET_PORT: 8000
      WEBSOCKET_HOST: "0.0.0.0"  # Escucha en todas las interfaces
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PING_INTERVAL: 10
      PING_TIMEOUT: 5
      POLL_INTERVAL: 5
    networks:
      - proyecto-autonomo-network
    restart: unless-stopped
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend/API (Node.js)
  markplace:
    build:
      context: ./Markplace
      dockerfile: Dockerfile
    container_name: proyecto-autonomo-markplace
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # Añade otras vars según tu config
    depends_on:
      - websoker  # Markplace depende de websoker
    networks:
      - proyecto-autonomo-network
    restart: unless-stopped
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proyecto-autonomo-network:
    driver: bridge
