# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.2.0'

# Framework web ligero
gem 'sinatra', '~> 3.1'
gem 'sinatra-contrib', '~> 3.1'

# GraphQL
gem 'graphql', '~> 2.1'

# Base de datos
gem 'pg', '~> 1.5'
gem 'activerecord', '~> 7.1'
gem 'standalone_migrations', '~> 7.1'

# HTTP y CORS
gem 'rack-cors', '~> 2.0'
gem 'puma', '~> 6.4'

# Utilidades
gem 'dotenv', '~> 2.8'
gem 'json', '~> 2.7'

# Logging
gem 'logger', '~> 1.6'

group :development, :test do
  gem 'pry', '~> 0.14'
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'factory_bot', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'database_cleaner-active_record', '~> 2.1'
end

group :development do
  gem 'rubocop', '~> 1.57', require: false
  gem 'rubocop-performance', '~> 1.19', require: false
  gem 'rerun', '~> 0.14'
end
